import React, { useEffect, useRef } from 'react';

interface ResultOverlayProps {
  result: 'accepted' | 'rejected' | null;
  inputString: string;
  stepCount: number;
  mistakes: number;
  onReset: () => void;
}

function Confetti() {
  const colors = ['#5c6ef8','#22c55e','#f59e0b','#ec4899','#06b6d4','#a855f7'];
  return (
    <div style={{ position: 'fixed', inset: 0, pointerEvents: 'none', zIndex: 200, overflow: 'hidden' }}>
      {Array.from({ length: 60 }).map((_, i) => (
        <div
          key={i}
          style={{
            position: 'absolute',
            top: '-20px',
            left: `${Math.random() * 100}%`,
            width: `${6 + Math.random() * 8}px`,
            height: `${6 + Math.random() * 8}px`,
            background: colors[Math.floor(Math.random() * colors.length)],
            borderRadius: Math.random() > 0.5 ? '50%' : '2px',
            animation: `confetti-fall ${1.5 + Math.random() * 2}s ease ${Math.random() * 0.8}s forwards`,
          }}
        />
      ))}
    </div>
  );
}

export default function ResultOverlay({ result, inputString, stepCount, mistakes, onReset }: ResultOverlayProps) {
  if (!result) return null;

  const accepted = result === 'accepted';

  return (
    <>
      {accepted && <Confetti />}

      {/* Backdrop */}
      <div style={{
        position: 'fixed', inset: 0,
        background: 'rgba(15, 23, 42, 0.4)',
        backdropFilter: 'blur(8px)',
        zIndex: 100,
        display: 'flex', alignItems: 'center', justifyContent: 'center',
        animation: 'fadeUp 0.25s ease',
      }}>
        {/* Card */}
        <div style={{
          background: 'var(--surface)',
          border: '1px solid var(--border-strong)',
          borderRadius: 'var(--radius-xl)',
          padding: '40px 48px',
          textAlign: 'center',
          boxShadow: 'var(--shadow-lg)',
          maxWidth: '380px',
          width: '90%',
          animation: 'popIn 0.35s cubic-bezier(0.34, 1.56, 0.64, 1)',
        }}>
          {/* Big emoji */}
          <div style={{ fontSize: '56px', marginBottom: '16px', lineHeight: 1 }}>
            {accepted ? '🎉' : '❌'}
          </div>

          {/* Title */}
          <h2 style={{
            fontSize: '24px', fontWeight: 700,
            color: accepted ? 'var(--green)' : 'var(--red)',
            marginBottom: '8px',
          }}>
            {accepted ? 'String Accepted!' : 'String Rejected'}
          </h2>

          {/* Input string */}
          <div style={{
            fontFamily: 'var(--font-mono)',
            fontSize: '18px',
            fontWeight: 600,
            color: 'var(--text)',
            padding: '10px 20px',
            background: accepted ? 'var(--green-light)' : 'var(--red-light)',
            border: `1.5px solid ${accepted ? 'var(--green-border)' : 'var(--red-border)'}`,
            borderRadius: 'var(--radius-sm)',
            marginBottom: '20px',
            display: 'inline-block',
          }}>
            "{inputString || 'ε'}"
          </div>

          {/* Stats */}
          {accepted && (
            <div style={{
              display: 'flex', gap: '16px', justifyContent: 'center', marginBottom: '24px',
            }}>
              <div style={{ textAlign: 'center' }}>
                <div style={{ fontSize: '22px', fontWeight: 700, color: 'var(--accent)' }}>{stepCount}</div>
                <div style={{ fontSize: '11px', color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.06em' }}>Steps</div>
              </div>
              <div style={{ width: '1px', background: 'var(--border)' }} />
              <div style={{ textAlign: 'center' }}>
                <div style={{ fontSize: '22px', fontWeight: 700, color: mistakes > 0 ? 'var(--amber)' : 'var(--green)' }}>{mistakes}</div>
                <div style={{ fontSize: '11px', color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.06em' }}>Mistakes</div>
              </div>
              <div style={{ width: '1px', background: 'var(--border)' }} />
              <div style={{ textAlign: 'center' }}>
                <div style={{ fontSize: '22px', fontWeight: 700, color: 'var(--green)' }}>
                  {Math.max(0, 100 - mistakes * 10)}
                </div>
                <div style={{ fontSize: '11px', color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.06em' }}>Score</div>
              </div>
            </div>
          )}

          {!accepted && (
            <p style={{ color: 'var(--text-muted)', fontSize: '13px', marginBottom: '24px', lineHeight: 1.6 }}>
              The string <strong>"{inputString}"</strong> is not in the language generated by this grammar.
              No valid derivation path exists.
            </p>
          )}

          {/* Buttons */}
          <div style={{ display: 'flex', gap: '10px', justifyContent: 'center' }}>
            <button
              onClick={onReset}
              style={{
                padding: '10px 24px',
                borderRadius: 'var(--radius-sm)',
                border: '1.5px solid var(--accent)',
                background: 'var(--accent)',
                color: 'white',
                fontFamily: 'var(--font-ui)',
                fontWeight: 600,
                fontSize: '14px',
                cursor: 'pointer',
              }}
            >
              Try Another String
            </button>
          </div>
        </div>
      </div>
    </>
  );
}
